services:
  tf:
    image: hashicorp/terraform:1.13.3
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - TF_WORKSPACE=${TF_WORKSPACE}
      